'use client';
import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import { CreditCard, ShieldCheck } from 'lucide-react';
import { Vazirmatn } from 'next/font/google';
import { prepareConsultationPayment } from '@/lib/api/consultations';
import { formatPersianDate, formatTime24 } from '@/lib/persianDateTime';
const vazir=Vazirmatn({subsets:['arabic'],weight:['400','500','600','700','800']});const fa=new Intl.NumberFormat('fa-IR');
export default function ConsultationPaymentPage(){const id=useSearchParams().get('consultation_id');const [data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{if(!id){setError('رزرو موقت مشخص نیست.');return}prepareConsultationPayment(id).then(setData).catch(e=>setError(e?.message||'آماده‌سازی پرداخت انجام نشد.'))},[id]);if(error)return <div className="p-10 text-center text-red-700">{error}</div>;if(!data)return <div className="p-10 text-center">در حال آماده‌سازی پرداخت...</div>;const c=data.consultation;return <main dir="rtl" className={`${vazir.className} min-h-screen bg-[#f6f9f7] px-5 py-6 md:px-8`}><div className="mx-auto max-w-2xl"><section className="rounded-3xl border bg-white p-6"><div className="flex items-center gap-3"><div className="rounded-xl bg-[#edf6f2] p-3 text-[#17634f]"><CreditCard/></div><div><h1 className="text-2xl font-black text-[#173f38]">پرداخت مشاوره</h1><p className="mt-1 text-xs text-slate-500">مرحله نهایی رزرو</p></div></div><div className="mt-6 space-y-3 rounded-2xl bg-slate-50 p-5 text-sm"><p>وکیل: <b>{c.lawyer?.full_name}</b></p><p>زمان: <b>{formatPersianDate(c.scheduled_start_at)} ساعت {formatTime24(c.scheduled_start_at)}</b></p><p>مدت: <b>{c.duration_minutes} دقیقه</b></p><p className="text-lg">مبلغ: <b className="text-[#17634f]">{fa.format(Math.round((c.price_rial||0)/10))} تومان</b></p></div><div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-7 text-amber-800"><ShieldCheck className="ml-1 inline" size={17}/>{data.gateway_message}</div><button disabled className="mt-5 w-full rounded-xl bg-[#173f38] px-5 py-3.5 text-sm font-black text-white opacity-45">ورود به درگاه پرداخت</button></section></div></main>}
