'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { ArrowRight, Clock3, CreditCard } from 'lucide-react';
import { Vazirmatn } from 'next/font/google';
import { cancelConsultationHold, getConsultation } from '@/lib/api/consultations';
import { formatPersianDate, formatTime24 } from '@/lib/persianDateTime';
const vazir=Vazirmatn({subsets:['arabic'],weight:['400','500','600','700','800']}); const fa=new Intl.NumberFormat('fa-IR');
export default function ConsultationReviewPage(){const params=useSearchParams(),router=useRouter(),id=params.get('consultation_id');const [item,setItem]=useState(null),[error,setError]=useState(''),[now,setNow]=useState(Date.now());useEffect(()=>{if(!id){setError('رزرو موقت مشخص نیست.');return}getConsultation(id).then(setItem).catch(e=>setError(e?.message||'دریافت جزئیات انجام نشد.'));const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[id]);const left=useMemo(()=>item?.hold_expires_at?Math.max(0,Math.floor((new Date(item.hold_expires_at).getTime()-now)/1000)):0,[item,now]);const mm=String(Math.floor(left/60)).padStart(2,'0'),ss=String(left%60).padStart(2,'0');async function back(){if(item?.status==='held')try{await cancelConsultationHold(item.public_id)}catch{}router.back()}if(error)return <div className="p-10 text-center text-red-700">{error}</div>;if(!item)return <div className="p-10 text-center">در حال دریافت...</div>;return <main dir="rtl" className={`${vazir.className} min-h-screen bg-[#f6f9f7] px-5 py-6 md:px-8`}><div className="mx-auto max-w-3xl"><button onClick={back} className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowRight size={16}/>بازگشت و انتخاب زمان دیگر</button><section className="mt-5 rounded-3xl border bg-white p-6"><h1 className="text-2xl font-black text-[#173f38]">بررسی و تأیید مشاوره</h1><div className="mt-4 rounded-xl bg-amber-50 p-4 text-sm font-bold text-amber-800"><Clock3 className="ml-1 inline" size={16}/>این زمان برای شما نگه داشته شده است: <span dir="ltr">{mm}:{ss}</span></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><Info label="موضوع" value={item.legal_request?.title||'مشاوره حقوقی'}/><Info label="دسته حقوقی" value={item.legal_request?.legal_category?.name||'—'}/><Info label="وکیل" value={item.lawyer?.full_name||'—'}/><Info label="تاریخ" value={formatPersianDate(item.scheduled_start_at)}/><Info label="ساعت" value={formatTime24(item.scheduled_start_at)}/><Info label="مدت" value={`${item.duration_minutes} دقیقه`}/><Info label="هزینه" value={item.price_rial?`${fa.format(Math.round(item.price_rial/10))} تومان`:'—'}/></div>{item.legal_request?.description?<div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">شرح مسئله</p><p className="mt-2 text-sm leading-7 text-slate-700">{item.legal_request.description}</p></div>:null}<button disabled={left<=0||item.status!=='held'} onClick={()=>router.push(`/client/consultations/payment?consultation_id=${encodeURIComponent(item.public_id)}`)} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#173f38] px-5 py-3.5 text-sm font-black text-white disabled:opacity-40"><CreditCard size={17}/>ادامه و پرداخت</button>{left<=0?<p className="mt-3 text-center text-xs font-bold text-red-600">مهلت نگه‌داری تمام شده است. دوباره زمان را انتخاب کنید.</p>:null}</section></div></main>}
function Info({label,value}){return <div className="rounded-xl border border-slate-200 p-4"><p className="text-xs font-bold text-slate-400">{label}</p><p className="mt-2 font-black text-[#294e46]">{value}</p></div>}
