import './globals.css';

import { Vazirmatn } from 'next/font/google';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const vazir = Vazirmatn({
    subsets: ['arabic'],
    weight: ['400', '500', '600', '700', '800'],
    variable: '--font-vazir',
    display: 'swap',
    preload: false,
});

export const metadata = {
    title: 'وکیلم',
    description: 'Generated by create next app',
    icons: {
        icon: '/logo.svg',
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="fa">
            <body
                className={`flex min-h-screen flex-col ${vazir.className} ${vazir.variable}`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
