import './globals.css';



import { Vazirmatn } from 'next/font/google';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

const vazir = Vazirmatn({
    subsets: ['arabic'],
    weight: ['400', '500', '700'],
    variable: '--font-vazir',
});

export const metadata = {
    title: 'وکیلم',
    description: 'Generated by create next app',
    icons: {
        icon: '/logo.svg',
    },
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`flex min-h-screen flex-col ${vazir.variable}`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
