'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { Check, Pencil, Plus, Save, Trash2, X } from 'lucide-react';
import { Vazirmatn } from 'next/font/google';
import PersianDatePicker from '@/components/common/PersianDatePicker';
import Time24Input from '@/components/common/Time24Input';
import { formatPersianDate, formatTime24, splitLocal, toIsoFromLocal } from '@/lib/persianDateTime';
import { createLawyerAvailability, deleteLawyerAvailability, getConsultationRates, getLawyerAvailabilities, getLawyerConsultations, saveConsultationRates, updateLawyerAvailability } from '@/lib/api/consultations';

const vazir=Vazirmatn({subsets:['arabic'],weight:['400','500','600','700','800']});
const DURATIONS=[15,30,45,60];
const statusLabel={held:'در انتظار پرداخت',reserved:'رزرو شده',confirmed:'تأیید شده',completed:'برگزار شده',cancelled:'لغو شده',expired:'منقضی شده',no_show:'عدم حضور'};
const fa=new Intl.NumberFormat('fa-IR');

export default function LawyerConsultationsPage(){
 const [availabilities,setAvailabilities]=useState([]); const [consultations,setConsultations]=useState([]); const [rates,setRates]=useState({15:'',30:'',45:'',60:''});
 const [form,setForm]=useState({date:'',start:'09:00',end:'10:00',durations:[30,60],note:''}); const [editingId,setEditingId]=useState(null);
 const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(''); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
 const load=useCallback(async()=>{try{const [a,c,r]=await Promise.all([getLawyerAvailabilities(),getLawyerConsultations(),getConsultationRates()]);setAvailabilities(a??[]);setConsultations(c??[]);const next={15:'',30:'',45:'',60:''};(r??[]).forEach(x=>{next[x.duration_minutes]=Math.round(Number(x.price_rial)/10).toString()});setRates(next);setError('')}catch(e){setError(e?.message||'دریافت اطلاعات مشاوره انجام نشد.')}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const upcoming=useMemo(()=>consultations.filter(x=>!['cancelled','expired','completed'].includes(x.status)&&new Date(x.scheduled_end_at)>new Date()),[consultations]);
 const toggle=d=>setForm(p=>({...p,durations:p.durations.includes(d)?p.durations.filter(x=>x!==d):[...p.durations,d].sort((a,b)=>a-b)}));
 const reset=()=>{setEditingId(null);setForm({date:'',start:'09:00',end:'10:00',durations:[30,60],note:''})};
 const edit=item=>{const a=splitLocal(item.starts_at),b=splitLocal(item.ends_at);setEditingId(item.id);setForm({date:a.date,start:a.time,end:b.time,durations:item.allowed_durations??DURATIONS,note:item.note??''});window.scrollTo({top:0,behavior:'smooth'})};
 async function saveRates(){setBusy('rates');setError('');setNotice('');try{const payload=DURATIONS.map(d=>({duration_minutes:d,price_rial:Math.round(Number(rates[d]||0)*10)}));await saveConsultationRates(payload);setNotice('تعرفه‌ها ذخیره شد.');await load()}catch(e){setNotice('');setError(e?.validationMessages?.[0]||e?.message||'ذخیره تعرفه انجام نشد.')}finally{setBusy('')}}
 async function submit(){const starts_at=toIsoFromLocal(form.date,form.start),ends_at=toIsoFromLocal(form.date,form.end);if(!starts_at||!ends_at||!form.durations.length){setNotice('');setError('تاریخ، ساعت شروع و پایان و حداقل یک مدت را مشخص کنید.');return}setBusy('save');setError('');setNotice('');try{const payload={starts_at,ends_at,allowed_durations:form.durations,note:form.note.trim()||null};editingId?await updateLawyerAvailability(editingId,payload):await createLawyerAvailability(payload);setNotice(editingId?'بازه آزاد ویرایش شد.':'بازه آزاد ثبت شد.');reset();await load()}catch(e){setNotice('');setError(e?.validationMessages?.[0]||e?.message||'ثبت بازه آزاد انجام نشد.')}finally{setBusy('')}}
 async function remove(id){if(!window.confirm('این بازه آزاد حذف شود؟'))return;setBusy(id);setError('');setNotice('');try{await deleteLawyerAvailability(id);setNotice('بازه آزاد حذف شد.');await load()}catch(e){setNotice('');setError(e?.message||'حذف بازه انجام نشد.')}finally{setBusy('')}}
 return <main dir="rtl" className={`${vazir.className} min-h-screen bg-[#f6f9f7] px-4 py-8 sm:px-6 lg:px-10`}><div className="mx-auto max-w-[1180px]">
  <header><p className="text-sm font-bold text-[#a47b2c]">پنل وکیل</p><h1 className="mt-2 text-3xl font-black text-[#173f38]">مشاوره‌های من</h1><p className="mt-2 text-sm leading-7 text-slate-500">تعرفه و زمان‌های آزاد مشاوره را مدیریت کنید. شروع availability می‌تواند حتی یک دقیقه بعد باشد؛ موکل فقط زمان‌هایی را می‌بیند که حداقل ۶۰ دقیقه تا شروعشان مانده باشد.</p></header>
  {error?<div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-700">{error}</div>:null}{notice?<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-700">{notice}</div>:null}
  <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="font-black text-[#173f38]">تعرفه مشاوره</h2><p className="mt-1 text-xs text-slate-500">مبالغ را به تومان وارد کنید.</p></div><Save className="text-[#a47b2c]"/></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{DURATIONS.map(d=><label key={d} className="text-xs font-bold text-slate-600">{d} دقیقه<input inputMode="numeric" value={rates[d]} onChange={e=>setRates(p=>({...p,[d]:e.target.value.replace(/\D/g,'')}))} placeholder="مبلغ تومان" className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 outline-none focus:border-[#76a99c]"/></label>)}</div><button type="button" disabled={busy==='rates'} onClick={saveRates} className="mt-4 rounded-xl bg-[#173f38] px-5 py-3 text-sm font-black text-white disabled:opacity-50">{busy==='rates'?'در حال ذخیره...':'ذخیره تعرفه‌ها'}</button></section>
  <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-5 md:p-6"><div className="flex items-center justify-between"><div><h2 className="font-black text-[#173f38]">{editingId?'ویرایش بازه آزاد':'افزودن بازه آزاد'}</h2><p className="mt-1 text-xs text-slate-500">تقویم شمسی است و ساعت‌ها به‌صورت ۲۴ ساعته ثبت می‌شوند.</p></div>{editingId?<button onClick={reset} className="inline-flex items-center gap-1 text-xs font-bold text-slate-500"><X size={15}/>انصراف</button>:<Plus className="text-[#a47b2c]"/>}</div>
   <div className="mt-5 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><PersianDatePicker value={form.date} onChange={date=>setForm(p=>({...p,date}))}/><div className="space-y-4"><label className="block text-xs font-bold text-slate-600">از ساعت (۲۴ ساعته)<div className="mt-2"><Time24Input value={form.start} onChange={start=>setForm(p=>({...p,start}))}/></div></label><label className="block text-xs font-bold text-slate-600">تا ساعت (۲۴ ساعته)<div className="mt-2"><Time24Input value={form.end} onChange={end=>setForm(p=>({...p,end}))}/></div></label><label className="block text-xs font-bold text-slate-600">یادداشت اختیاری<input value={form.note} onChange={e=>setForm(p=>({...p,note:e.target.value}))} className="mt-2 h-12 w-full rounded-xl border border-slate-200 px-3 outline-none focus:border-[#76a99c]"/></label></div></div>
   <div className="mt-5"><p className="text-xs font-bold text-slate-600">مدت‌های قابل رزرو</p><div className="mt-2 flex flex-wrap gap-2">{DURATIONS.map(d=>{const active=form.durations.includes(d);return <button key={d} type="button" onClick={()=>toggle(d)} className={`inline-flex items-center gap-1.5 rounded-xl border px-4 py-2.5 text-xs font-black ${active?'border-[#c7a154] bg-[#fff8e7] text-[#6e541d]':'border-slate-200 text-slate-500'}`}>{active?<Check size={14}/>:null}{d} دقیقه</button>})}</div></div>
   <button type="button" disabled={busy==='save'} onClick={submit} className="mt-5 rounded-xl bg-[#173f38] px-6 py-3 text-sm font-black text-white disabled:opacity-50">{busy==='save'?'در حال ثبت...':editingId?'ذخیره تغییرات':'ثبت بازه آزاد'}</button>
  </section>
  <section className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-black text-[#173f38]">بازه‌های آزاد آینده</h2></div>{loading?<p className="p-10 text-center text-sm text-slate-500">در حال دریافت...</p>:!availabilities.length?<p className="p-10 text-center text-sm text-slate-500">هنوز بازه آزادی ثبت نکرده‌اید.</p>:<div className="divide-y divide-slate-100">{availabilities.map(item=><article key={item.id} className="flex flex-col justify-between gap-4 p-5 md:flex-row md:items-center"><div><p className="font-black text-[#294e46]">{formatPersianDate(item.starts_at)}</p><p className="mt-2 text-xs text-slate-500">{formatTime24(item.starts_at)} تا {formatTime24(item.ends_at)} • {(item.allowed_durations??[]).map(d=>`${d} دقیقه`).join('، ')}</p></div><div className="flex gap-2"><button onClick={()=>edit(item)} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-xs font-bold"><Pencil size={14}/>ویرایش</button><button onClick={()=>remove(item.id)} className="inline-flex items-center gap-1 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-xs font-bold text-red-700"><Trash2 size={14}/>حذف</button></div></article>)}</div>}</section>
  <section className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-black text-[#173f38]">رزروهای آینده</h2></div>{!upcoming.length?<p className="p-10 text-center text-sm text-slate-500">رزرو فعالی ندارید.</p>:<div className="divide-y divide-slate-100">{upcoming.map(item=><article key={item.public_id} className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black text-[#294e46]">{item.legal_request?.title||'مشاوره حقوقی'}</p><p className="mt-2 text-xs text-slate-500">{item.client?.name||'موکل'} • {formatPersianDate(item.scheduled_start_at)} • {formatTime24(item.scheduled_start_at)} • {item.duration_minutes} دقیقه • {item.price_rial?`${fa.format(Math.round(item.price_rial/10))} تومان`:''}</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">{statusLabel[item.status]||'در حال پیگیری'}</span></div></article>)}</div>}</section>
 </div></main>;
}
