<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Concerns\HasUuids;

class LawyerMatchRun extends Model
{
    use HasUuids;

    /** The table has created_at but no updated_at column. */
    public const UPDATED_AT = null;

    /** Attributes that may be mass assigned. */
    protected $fillable = [
        'legal_request_id',
        'algorithm_version',
        'status',
        'candidates_count',
        'completed_at',
    ];

    /**
     * Cast database values to useful PHP types.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'candidates_count' => 'integer',
            'completed_at' => 'datetime',
        ];
    }

    /** Legal request being matched. */
    public function legalRequest()
    {
        return $this->belongsTo(LegalRequest::class);
    }

    /** Candidate lawyersAdmin generated by this matching run. */
    public function candidates()
    {
        return $this->hasMany(LawyerMatchCandidate::class, 'match_run_id');
    }

}
